### PR TITLE
fsstore to fail when the root dir does not exist

### LINKED ISSUE #724: mixs server requires --configStoreURL yet it can be bogus without even a warning
``` bash
./mixer/bazel-bin/cmd/server/mixs server --logtostderr
Missing configStoreURL
```
vs
```
./mixer/bazel-bin/cmd/server/mixs server --configStoreURL=fs://this/does/not/exist --logtostderr
I0517 02:27:23.270369   14408 manager.go:191] Loaded new config fsStore: this/does/not/exist
Starting Config API server on port 9094
Starting self-monitoring on port 9093
Istio Mixer: version: unknown (build: 2017-05-17-9da7b34, status: Clean)
Starting gRPC server on port 9091
```

### PR DESCRIPTION
**Pull request by jmuk**
fixes #724

---
This change is [Reviewable](https://reviewable.io/reviews/istio/mixer/786)

### CODE REVIEW

File: pkg/config/fsstore.go [hunk 1]
```diff
@@ -52,7 +52,12 @@ type readFileFunc func(filename string) ([]byte, error)
 type mkdirAllFunc func(path string, perm os.FileMode) error
 type removeFunc func(name string) error
 
-func newFSStore(root string) KeyValueStore {
+func newFSStore(root string) (KeyValueStore, error) {
+	if finfo, err := os.Stat(root); err != nil {
+		return nil, err
+	} else if !finfo.IsDir() {
```
Comment (rkpagadala) [inline pkg/config/fsstore.go]: No need for else since if returns, easier to read and reason that way

Comment (jmuk) [inline pkg/config/fsstore.go]: done
